const asyncHandler = (fn) => async (req, res, next) => {
  try {
    await fn(req, res, next);
  } catch (error) {
    res.status(error.code || 500).json({
      success: false,
      message: error.message || `Error occured in our application: ${error}`,
    });
  }
};

export default asyncHandler;
